### ISSUE TITLE
Перенести все блоки в папку с блоками

### ISSUE THREAD

**Issue by chmnkh** [alextsk/cv-markup#13]
```
 section.intro
    .intro__mugshot
    .intro__name(contenteditable)=data.name
    .intro__surname(contenteditable)=data.surname
       p.intro__profession=data.profession
```
Это же тоже блок, не нужно какие-то блоки делать "особенными" :)
Так что перенеси все подобные штуки в свою папку, как и все остальные блоки, и сделай для них миксины.

**Comment by chmnkh** [comment]
Смотри, [эта штука](https://github.com/alextsk/cv-markup/pull/21) по ошибке закрылась, когда я вмержил одну из веток.
Посмотри там замечания, внеси исправления в эту же ветку, и новый пулл реквест создай.
Далее, когда ты исправляешь замечания, чтобы каши не было, процесс такой:
1) начинаешь всегда (!) с основной ветки (у тебя это refactoring, получается);
2) создаешь от этой самой (!) ветки ветку для одного (!) ишью;
3) решаешь там проблему, обозначенную ТОЛЬКО (!) в этом ишью, не надо распыляться на несколько ишью сразу;
4) создаешь для этой ветки пулл реквест;
5) когда переходишь к исправлению следующего ишью начинаешь с п.1: git checkout refactoring, git checkout -b новая ветка, потом пункт 3 и так далее.

**Comment by alextsk** [comment]
что делать если исправление одного ишью решает частично другое (ненамеренно, например когда импорт класса убирал из миксина отпала необходимость в конкатенации строк)? cherry-pick из несмерженной ветки законно делать?

**Comment by chmnkh** [comment]
Ну тебе Сергей уже на риззоме ответил что как делать, мы обсудили и сошлись на том, что я немного перегнул палку)

**Comment by alextsk** [comment]
да, я видел, просто сюда раньше написал)

**Comment by chmnkh** [comment]
Я правильно понял, что у тебя ветка по #25 включает в себя изменения по этом и по #14 ишью? Если так, можешь эти ишью и соответствующие пулл реквесты позакрывать просто.

**Comment by chmnkh** [comment]
Если уж мы решили что можно бренч для ишью от бренча для ишью делать, ссылайся плиз тогда на это в мессаджах пулл реквеста, ты так вроде раньше делал, чтобы не пришлось проверять сидеть это)

**Comment by alextsk** [comment]
не помню где я на это ссылался. я ссылался когда при правке одного ишью другое стало неактуально, т.е. вроде как один пулл реквест закрыл несколько. а вообще я стараюсь за один пулл реквест одно закрывать, отбранчиваюсь просто чтоб конфликтов меньше было при мерже

**Comment by alextsk** [comment]
новые ветки я как раз от базовой сделал как ты написал, просто черрипиком коммиты из соседних туда забрал
