### ISSUE TITLE
Самодостаточность блоков

### ISSUE THREAD

**Issue by chmnkh** [alextsk/cv-markup#15]
Все файлы, которые касаются блоков: стили, скрипты, верстка и т.д., должны находится рядом, в директории блока. У тебя щас со стилями каша небольшая получается: для каких-то блоков стили определены в каких-то общих файлах, для других блоков - нет.
```
mixin ratingDots(arr, baseClass)
    - var defStyle = loadStyle("src/components/rating-dots/rating-dots.styl", baseClass);
```
Такие штуки тоже не надо делать. Задай блоку какой-нибудь класс, его и используй.

**Comment by chmnkh** [comment]
Вообще из pug файла не надо в стили лезть)

**Comment by alextsk** [comment]
я, конечно, переделаю. но у меня вопрос: чем лучше лезть в стили из js и подбирать это вебпаковским лоадером?  при том у компонента вообще может не быть скриптов, но хтмл точно будет.
и еще вопрос, вот эта конструкция 
` - var derived = data.education.map( i => ({title: i.degree, subtitle: i.univer, interval : i.interval, copy: i.copy}));
                        +places(derived, "education")(title='emph')`
позволяет мне собирать блоки с почти одинаковым представлением но разной семантикой. если я не передаю базовый класс у меня будет два разных компонента с одинаковыми стилями, и любые изменения придется дублировать. как мне этого избежать?
