### ISSUE TITLE
Держать стили для блоков в одном месте

### ISSUE THREAD

**Issue by chmnkh** [alextsk/cv-markup#29]
```
.contact__head:before
  background-image: url(../img/contact.svg)
.skills__head:before
  background-image: url(../img/skills.svg)
.education__head:before
  background-image: url(../img/education.svg)
.software__head:before
  background-image: url(../img/software.svg)
.profile__head:before
  background-image: url(../img/profile.svg)
.experience__head:before
  background-image: url(../img/experience.svg)  
```
Все стили для блока должны в одном месте лежать. Не нужно ничего в глобальную область выносить, как ты здесь сделал.

**Comment by chmnkh** [comment]
```
h1, h2, h3
  text-transform uppercase
  white-space nowrap
  font-family 'Conv_MyriadPro-Bold'
```
Такие штуки тоже делать не нужно, это все тоже должно быть в рамках блока быть и повешано на нужные классы.

**Comment by alextsk** [comment]
т.е. общих стилей сайта вообще не может быть? у каждого блока свои?

**Comment by chmnkh** [comment]
Общие стили есть, но они как правило ограничиваются штуками типа
```
* {
  box-sizing: border-box;
}
```
или стилями на какие-то рутовые компоненты, в которые потом все приложение маунтиться, типа такого:
```
#root {
  min-height: 100%;

  @include themed('background-color', 'app-background-color');
}
```
или всякие стили на html и body
```
body {
  margin: 0;
  padding: 0;
  font-family: 'Work Sans', sans-serif;
  font-size: 1rem;
}

html,
body {
  height: 100%;
}
```
Но со стилями на любые другие теги типа h1, h2, h3, как у тебя сделано, аккуратно надо быть. Все таки если мы с блоками работаем, а блоки нужно максимально самодостаточными делать (исключаем опять же box-sizing: border-box на все элементы, как у нас принято делать), то неправильно где-то там глобально для каких-то тегов стили определять, от которых у тебя блоки по сути зависимы станут, и уж тем более в глобальных стилях писать правила для элементов блоков. Если ты захочешь эти блоки в другом месте использовать, тебе что, придется за собой эти глобальные стили подтягивать? Или если ты внезапно добавишь в проект другой блок с h2 или h3, у тебя получается эти глобальные стили будут на этот блок влиять, а вдруг тебе это не надо?

**Comment by chmnkh** [comment]
Про стили на элементы блоков в общих стилях я не высказался, но думаю тоже понятно.

**Comment by alextsk** [comment]
как тогда лучше сделать чтобы не копипастить одинаковые стили - вынести заголовки в отдельный блок или миксины в stylus?

**Comment by chmnkh** [comment]
то что у тебя скопипастится вот это 
```
  text-transform uppercase
  white-space nowrap
  font-family 'Conv_MyriadPro-Bold'
```
это ничего страшного. У тебя блоки вообще не должны ничего о других блоках знать и уж тем более на какие-то глобальные стили полагаться, у тебя так и так какие-то стили "копипаститься" будут. Если я два элемента разных блока, например, спозиционирую абсолютно, будет ли это копипастой вообще считаться?)
