### ISSUE TITLE
Семантическое именование блоков

### ISSUE THREAD

**Issue by chmnkh** [alextsk/cv-markup#33]
Блок definitions так называется, потому что он содержит тег dl, или блок definitions с параметром personalInfo какой-то смысл все-таки имеет?

**Comment by alextsk** [comment]
по идее это должен был быть абстрактный блок принимающий список с любыми определениями, не обязательно контакты. personalInfo там появился в результате #25.  как сделать generic блок и не называть параметр data?

**Comment by chmnkh** [comment]
То ишью с именованием переменных я тебе оставлял, потому что ну очень много где у тебя были имена чересчур абстрактные, всякие arr и data были сплошь и рядом. В каком-то случае data на самом деле норм, например это - норм.
```
mixin person(data)
```
если бы ты тут назвал например data, было бы уже сильно хуже, потому что placesList - прям хорошее название, сразу понятно что за параметр
```
mixin places(placesList)
```
По поводу definitions: здесь можешь в принципе data сделать, хотя мне больше бы понравилось definitions, но это неоднозначно, на твое усмотрение. Но вот дженерик блок definitions с какой-то personalInfo и contactData(Name) - это уже странно. 
Кстати говоря у тебя в этом блоке еще не предусмотрены варианты со ссылками, а ведь там еще и ссылки есть)
