### ISSUE TITLE
Шрифты подключены не по стандарту

### ISSUE THREAD

**Issue by chmnkh** [alextsk/cv-markup#34]
Почитай на риззоме как шрифты подключать в стандартах, они у тебя неверно сейчас подключены.

**Comment by alextsk** [comment]
lower-case-hyphenated ?

**Comment by chmnkh** [comment]
!Разные начертания одного и того же шрифта подключайте под одним именем, но для разных font-weight и font-style 

!Всегда использовать как минимум один запасной шрифт и одно запасное семейство
