### ISSUE TITLE
@require в style.styl

### ISSUE THREAD

**Issue by Sha1fei** [alextsk/cv-markup#41]
Нужно избавить от @require и собирать автоматически, чтобы не помнить какие стили нужно подключать к проекты.

**Comment by alextsk** [comment]
автоматически на каком основании? просто все подряд, независимо используем или нет?

**Comment by Sha1fei** [comment]
В проекте должны быть только те файлы, которые непосредственно относятся к нему. Ты используешь где то min.svg? Объясни для чего рекваеришь variables в style.styl?

**Comment by alextsk** [comment]
min не использую. переменные из variables используются некоторыми компонентами

**Comment by Sha1fei** [comment]
а style.styl тут причем? Не используешь, удаляй.

**Comment by alextsk** [comment]
удалил
