### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Sha1fei** [alextsk/cv-markup#47]
Не подправлено 
![image](https://user-images.githubusercontent.com/31854808/44320603-31e0b280-a46d-11e8-8f48-f45d25d5ebc7.jpg)
![image1](https://user-images.githubusercontent.com/31854808/44320605-3311df80-a46d-11e8-8915-8a4da907e795.jpg)

**Comment by alextsk** [comment]
какой у тебя браузер? и ты точно исправленную ветку собрал? у меня вот так
![educ_margin](https://user-images.githubusercontent.com/16453186/44320967-71100300-a46f-11e8-8753-49a4daad65ee.png)
.
![soft_columns](https://user-images.githubusercontent.com/16453186/44321005-addbfa00-a46f-11e8-8fe1-2f816c5c5814.png)

**Comment by Sha1fei** [comment]
Я открыл gh-pages, chrome

**Comment by alextsk** [comment]
изменения протолкнул, сейчас все должно быть ок

**Comment by Sha1fei** [comment]
C софтваре все ок, но отступ остался.

**Comment by alextsk** [comment]
можешь посмотреть какой элемент дает отступ? или обновить кэш. у меня нет отступа, не знаю что исправлять

**Comment by Sha1fei** [comment]
в chrome dev отступ остался (даже после очистки кэша), а в просто chrome исчез. Ок, ишью закрываю. По этому макету у меня больше нет замечаний.
